# Generated by Django 4.0.4 on 2022-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.FileField(default='', upload_to='tools/<function device_upload_image at 0x00000170C35D0310>'),
        ),
    ]
