# Generated by Django 4.0.4 on 2022-05-27 10:51

import apiv1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_alter_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.FileField(default='', upload_to=apiv1.models.device_upload_image),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
