# Generated by Django 4.0.4 on 2022-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_alter_tool_image_alter_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
